import { Toaster } from "@/components/ui/toaster";
import "../globals.css";
import 'easymde/dist/easymde.min.css';
export const metadata = {
  title: "Cyfotok Academy - Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-black overflow-y-scroll">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
